[package]
name = "rbxdom_rust_exporter"
version = "0.1.0"
edition = "2024"

[dependencies]
rbx_binary = "1.0.0"
rbx_types = "2.0.0"
rbx_dom_weak = "3.0.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "=1.0.140"
anyhow = "1.0"
