
[package]
name = "LuneX"
version = "0.2.0"
edition = "2021"

[[bin]]
name = "LuneX"
path = "src/main.rs"

[dependencies]
rbx_binary = "1.0.0"
rbx_types = "2.0.0"
rbx_dom_weak = "3.0.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "=1.0.140"
anyhow = "1.0"
rfd = "0.14"
