name: LuneX Export
on:
  push:
    tags:
      - 'v*'
jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Build and Export
        run: |
          bash scripts/create_release.sh ${{ github.ref_name }}
      - name: Upload Release Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: LuneX Release ${{ github.ref_name }}
          path: releases/
